[package]
name = "ream-network-spec"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["devnet5"]
devnet5 = []

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
ethereum_serde_utils.workspace = true
serde.workspace = true
serde_yaml.workspace = true
tracing.workspace = true

# ream-dependencies
ream-consensus-misc.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
